(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
flowHornSchunck[i_,length_,{{f1_,f1x_},{f2_,f2x_}},lamda_]:=Block[{u,u1,mask,fx,ft,uav,p,d},(

(*We define fx*)
fx[x_]:=0.5*(f1x[x]+f2x[x]);

(*We define ft*)
ft[x_]:=f2[x]-f1[x];

mask={1,-2,1};
u=Table[0.,{k,length}];
u1=Table[0.,{k,length}];

Do[
Do[

uav=Mean[u[[x-1;;x+1]]*mask];
p=fx[x]*uav+ft[x];
d=lamda+fx[x]^2 ;
u1[[x]]=uav-fx[x]*p/d;
,{x,Range[2,length-1]}];

u=u1;
,{k,i}];

u
)]

flowHornSchunck::usage="
Input\[Rule] [i,length,{{f1,f1x},{f2,f2x}},lamda]
Output-> {1D OpticalFlow}
";



