(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
flowLukasKanade[i_,length_,{{f1_,f1x_},{f2_,f2x_}},lamda_]:=Block[{u,mask,fx,ft,uav,p,d,x1,t,u1},(

(*We define fx*)
fx[x_]:=0.5*(f1x[x]+f2x[x]);

(*We define ft*)
ft[x_]:=f2[x]-f1[x];

u=Table[0.,{k,length}];

Do[
x1=fx[#]&/@Range[x-lamda,x+lamda];
t=ft[#]&/@Range[x-lamda,x+lamda];
u1=-Total[t]/Total[x1];
u[[x]]=u1;
,{x,Range[1,length]}];
u
)
]

flowLukasKanade::usage="
Input\[Rule] [i,length,{{f1,f1x},{f2,f2x}},lamda]
lamda->window size
Output-> {1D OpticalFlow}
";





